### ISSUE TITLE
SOAP FAIL: Error: Request body larger than maxBodyLength limit

### ISSUE THREAD

**Issue by lfcoelho1** [circa10a/easy-soap-request#27]
We update to release to 3.0.1 and change code like discribe on: #24 

But now, generated other error:

![image](https://user-images.githubusercontent.com/29629143/66487457-bb44b100-ea82-11e9-9a1c-7c09f67f370b.png)

Anybody see this before?

**Comment by circa10a** [comment]
@lfcoelho1 Can you let me know if `3.1.0` resolves your issue?

**Comment by circa10a** [comment]
@lfcoelho1 can you `rm -rf node_modules/` then `npm install easy-soap-request@3.1.0 && npm install`. Ensure you have version `3.1.0`. This is a common axios issue and implemented [the documented resolution](https://github.com/axios/axios/issues/1362).

**Comment by circa10a** [comment]
@lfcoelho1 any updates

**Comment by Lynext** [comment]
I did not want to create a new issue, can you reopen this one as I'm currently getting the same error ? I do not always get this but sometimes I do. I have really long base64 string's in my soap request so that could be the reason. My quesiton is there any way to increase this limit if there is one ? How can I do it ? My easy-soap-request module's package.json says I'm on version "3.5.0". @circa10a

**Comment by circa10a** [comment]
@Lynext can you try passing `maxBodyLength: Infinity` to `easy-soap-request`?

**Comment by Lynext** [comment]
@circa10a Just tried now, still doesn't work. Getting the same error.

**Comment by circa10a** [comment]
@Lynext, do you know what web server you are sending data to? I suspect there is a max body size limit set via server side. In which case, you would need to work with who owns that web server

**Comment by Lynext** [comment]
Okay, thanks for the help :)
