### ISSUE TITLE
Question: Dynamically creating XML

### ISSUE THREAD

**Issue by StuartMorris0** [circa10a/easy-soap-request#33]
Whilst this is not directly an issue, more of a question, I thought it would be a good place to ask.

Do you know how I can dynamically create values within an XML file for the request? Your example reads a static XML file, which works great. I just wondered if you have any recommendations on building an XML file with dynamic values. Thanks

**Comment by circa10a** [comment]
Hi @StuartMorris0 . I used the read from file example just to keep the snippets short because XML can be lengthy. 

When you invoke the library, you supply the xml data as a string. However you choose to build that string, is up to you. In previous examples, I read from a file. But in reality, you would probably want to use something like [xmlbuilder](https://www.npmjs.com/package/xmlbuilder) or maybe concat some strings together.

Example:

```js
const soapRequest = require('easy-soap-request');

// Build XML
const someVar = 'something';
const string1 = '<xml1>one</xml>';
const string2 = `<xml2>${someVar}</xml2>`;

const someXml = `<payload>${string1}${string2}</payload>`;

// example data
const url = 'https://graphical.weather.gov/xml/SOAP_server/ndfdXMLserver.php';
const sampleHeaders = {
  'user-agent': 'sampleTest',
  'Content-Type': 'text/xml;charset=UTF-8',
  'soapAction': 'https://graphical.weather.gov/xml/DWMLgen/wsdl/ndfdXML.wsdl#LatLonListZipCode',
};


// usage of module
(async () => {
  const { response } = await soapRequest({ url: url, headers: sampleHeaders, xml: someXml, timeout: 1000 }); // Optional timeout parameter(milliseconds)
  const { headers, body, statusCode } = response;
  console.log(headers);
  console.log(body);
  console.log(statusCode);
})();
```

**Comment by StuartMorris0** [comment]
Awesome, that looks like a great package. Thanks for the feedback appreciate it
